stepshop/adminapp/urls.py
from django.urls import path

from .views import (user_create, users, user_update, user_delete,
                    category_create, categories, category_update, category_delete,
                    product_create, products, product_update, product_delete, product_read)

app_name = "adminapp"

urlpatterns = [
    path('users/create/', user_create, name='user_create'),
    path('users/read/', users, name='users'),
    path('users/update/<int:pk>/', user_update, name='user_update'),
    path('users/delete/<int:pk>/', user_delete, name='user_delete'),

    path('categories/create/', category_create, name='category_create'),
    path('categories/read/', categories, name='categories'),
    path('categories/update/<int:pk>/', category_update, name='category_update'),
    path('categories/delete/<int:pk>/', category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', product_create, name='product_create'),
    path('products/read/category/<int:pk>/', products, name='products'),
    path('products/update/<int:pk>/', product_update, name='product_update'),
    path('products/read/<int:pk>/', product_read, name='product_read'),
    path('products/delete/<int:pk>/', product_delete, name='product_delete'),
]

stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit

app_name = "authapp"

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('register/', register, name="register"),
    path('edit/', edit, name="edit"),
]

stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import index, about, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name="index"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="auth")),
    path('basket/', include('basketapp.urls', namespace="basket")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/adminapp/models.py
from django.db import models

# Create your models here.

stepshop/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, get_object_or_404

from authapp.models import ShopUser
from mainapp.models import Category, Product


@user_passes_test(lambda u: u.is_superuser)
def users(request):
    title = 'админка/пользователи'
    user_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')

    context = {
        'title': title,
        'objects': user_list
    }
    return render(request, 'adminapp/users.html', context)


def user_create(request):
    pass


def user_update(request, pk):
    pass


def user_delete(request, pk):
    pass


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'
    category_list = Category.objects.all()

    context = {
        'title': title,
        'objects': category_list
    }
    return render(request, 'adminapp/categories.html', context)


def category_create(request):
    pass


def category_update(request):
    pass


def category_delete(request):
    pass


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'админка/продукты'
    category = get_object_or_404(Category, pk=pk)
    product_list = Product.objects.filter(category__pk=pk).order_by('name')

    context = {
        'title': title,
        'category': category,
        'objects': product_list,
    }
    return render(request, 'adminapp/products.html', context)


def product_create(request):
    pass


def product_update(request):
    pass


def product_delete(request):
    pass


def product_read(request):
    pass
# , , , ,
#                    , , , ,
#                    , , , ,

stepshop/templates/adminapp/base.html
    <!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
<!-- Bootstrap core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'adminapp/style.css' %}">
        <link rel="stylesheet" type="text/css"href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css'>
        <link rel="stylesheet" type="text/css" href="{% static 'assets/css/fontawesome.css' %}">

    {% block css %}
    {% endblock %}


</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar|default:'avatar-default.png' }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'index' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">Admin`ka</span>
            </a>
            {% include 'adminapp/inludes/inc_admin_menu.html' %}
        </div>
        <a href="{% url 'auth:logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Выход</span> </a>
    </nav>
</div>
<!--Container Main start-->
<div class="height-100 bg-light">
    {% block content %}
    {% endblock %}
</div>
<!--Container Main end-->
    <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src='{% static 'adminapp/script.js' %}'></script>

    {% block js %}
    {% endblock %}
</body>
</html>

stepshop/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>

                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>

                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in objects %}
                            <tr {% if category.is_deleted %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{% url 'admin_staff:products' category.id %}" style="color: dodgerblue">{{ category.name }}</a></td>

                                <td>
                                    <a {% if category.is_deleted %} class="invisible" {% endif %} href="{#% url 'admin_staff:category_update' pk=category.id %#}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>
                              <td>
                                    <a {% if category.is_deleted %} class="invisible" {% endif %} href="{#% url 'admin_staff:category_delete' pk=category.id %#}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{#% url 'adminapp:category_create' %#}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

stepshop/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <h1 class="mt-4">Продукты
        {% if category %}
        <span>{{ category.name }}</span>
        {% endif %}
    </h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fa fa-table mr-1"></i>
            <a href="{% url 'admin_staff:categories' %}">Категории</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Изображение</th>
                        <th>Имя</th>
                        <th>Описание</th>
                        <th>Количество</th>
                        <th>Цена</th>
                        <th>Подробнее</th>
                        <th>Редактировать</th>
                        <th>Удалить</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Изображение</th>
                        <th>Имя</th>
                        <th>Описание</th>
                        <th>Количество</th>
                        <th>Цена</th>
                        <th>Подробнее</th>
                        <th>Редактировать</th>
                        <th>Удалить</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for object in objects %}
                    <tr>
                        <td><img src="/media/{{object.image|default:'products_images/default.jpg'}}"
                                 alt="{{ object.name }}" style="width:50px;">
                        </td>
                        <td>
                            {{ object.name|title }}
                        </td>
                        <td>
                            {{ object.short_desc|title }}
                        </td>
                        <td>{{ object.quantity }}</td>
                        <td>{{ object.price }} руб</td>
                        <td>
                            <button type="button" class="btn btn-primary">
                                <a class="text-white" href="{% url 'admin_staff:product_read' object.pk %}">
                                    <i class="fa fa-info-circle"></i>
                                </a>
                            </button>
                        </td>
                        <td>
                            <button class="btn btn-warning">
                                <a class="text-dark" href="{% url 'admin_staff:product_update' object.pk %}">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </button>
                        </td>
                        <td>
                            <button class="btn btn-danger">
                                <a class="text-white" href="{% url 'admin_staff:product_delete' object.pk %}">
                                    <i class="fa fa-times-circle"></i>
                                </a>
                            </button>
                        </td>
                    </tr>
                    {% endfor%}
                    </tbody>
                </table>

                <div class="card-footer">
                    <button class="btn btn-success">
                        <a class="text-white" href={% url 'admin_staff:product_create' category.pk %}>
                        новый продукт
                        </a>
                    </button>
                </div>

            </div>

            {% endblock %}

stepshop/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in objects %}
                            <tr {% if user.is_deleted %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{#% url 'admin_staff:user_update' user.id %#}" style="color: dodgerblue">{{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td>{{ user.last_login }}</td>
                                <td>
                                    <a {% if user.is_deleted %} class="invisible" {% endif %} href="{#% url 'admin_staff:user_delete' pk=user.id %#}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{#% url 'adminapp:user_create' %#}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}