stepshop/adminapp/urls.py
from django.urls import path

from .views import (user_create, users, user_update, user_delete,
                    category_create, categories, category_update, category_delete,
                    product_create, products, product_update, product_delete, product_read)

app_name = "adminapp"

urlpatterns = [
    path('users/create/', user_create, name='user_create'),
    path('users/read/', users, name='users'),
    path('users/update/<int:pk>/', user_update, name='user_update'),
    path('users/delete/<int:pk>/', user_delete, name='user_delete'),

    path('categories/create/', category_create, name='category_create'),
    path('categories/read/', categories, name='categories'),
    path('categories/update/<int:pk>/', category_update, name='category_update'),
    path('categories/delete/<int:pk>/', category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', product_create, name='product_create'),
    path('products/read/category/<int:pk>/', products, name='products'),
    path('products/update/<int:pk>/', product_update, name='product_update'),
    path('products/read/<int:pk>/', product_read, name='product_read'),
    path('products/delete/<int:pk>/', product_delete, name='product_delete'),
]

stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit

app_name = "authapp"

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('register/', register, name="register"),
    path('edit/', edit, name="edit"),
]

stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import index, about, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name="index"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="auth")),
    path('basket/', include('basketapp.urls', namespace="basket")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/templates/layout/base.html
{%load static%}

<!DOCTYPE html>
<html lang="ru">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>Bober inc{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tooplate-main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">


    <!--
    Tooplate 2114 Pixie
    https://www.tooplate.com/view/2114-pixie
    -->
</head>

<body>

<!-- Pre Header -->
<div id="pre-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 blue-menu text-light">
                {% if user.is_superuser %}
                <span>
                    <a href="{% url 'admin_staff:users' %}" class="text-light">
                            Админка
                    </a>
                    </span> |
                {% endif %}
                {% if user.is_authenticated %}
                    <span>
                            <a href="{% url 'auth:edit' %}" class="text-light">
                        {{user.username|title}}
                        </a>
                    </span> |
                    <span>
                        <a href="{% url 'auth:logout' %}" class="text-light">Выйти</a>
                    </span>
                {% else %}
                    <span>
                        <a href="{% url 'auth:login' %}" class="text-light">Войти</a>
                    </span>
                {% endif %}
                 {% if user.is_authenticated and basket  %}
                        | <a href="{% url 'basket:index' %}" class="text-light basket">
                            <span>{{ basket.0.total_quantity }}</span>
                        </a>

                        <span class = "price">${{ basket.0.total_cost|floatformat:"0g" }}</span>
                {% endif %}

            </div>
        </div>
    </div>
</div>

{% include '../includes/inc_main_menu.html'%}

{%block content%}
blockad
{% endblock %}

<!-- Sub Footer Starts Here -->
<div class="sub-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="copyright-text">
                    <p>Copyright &copy; 2023&ndash; {%now "Y" %} Bober Inc.

                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Sub Footer Ends Here -->


<!-- Bootstrap core JavaScript -->
<script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


<!-- Additional Scripts -->
<script src="{% static 'assets/js/custom.js' %}"></script>
<script src="{% static 'assets/js/owl.js' %}"></script>


<script language="text/Javascript">
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }

</script>
{% block js %}

{% endblock %}


</body>
</html>