stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit

app_name = "authapp"

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('register/', register, name="register"),
    path('edit/', edit, name="edit"),
]

stepshop/mainapp/urls.py
from django.urls import path

from mainapp.views import products, product

app_name = "products"

urlpatterns = [
    path('', products, name="index"),
    path('<int:pk>/', products, name="category"),
    path('product/<int:pk>/', product, name="product"),
]

stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import index, about, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name="index"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="auth")),
    path('basket/', include('basketapp.urls', namespace="basket")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/templates/includes/inc_category_menu.html
<div class="col-md-8 col-sm-12">
    <div id="filters" class="button-group">
        <button class="btn btn-primary
        {% if not category %}active{% endif %}">
            <a href="{% url 'products:index' %}">Все</a>
        </button>
        {% for cat in categories %}
        <button class="btn btn-primary
        {% if cat == category %}active{% endif %}">
            <a href="{% url 'products:category' cat.pk %}">
                {{ cat.name }}</a>
        </button>
        {% endfor %}

    </div>
</div>

stepshop/templates/includes/inc_main_menu.html
{%load static%}
{% load my_tags %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="#"><img src="{% static 'assets/images/header-logo.png' %}" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% for item in links_menu %}

               <li class="nav-item {% if not request.resolver_match.namespace and request.resolver_match.url_name == item.link or item.link|my_split in request.resolver_match.namespace %}active{% endif %}">
              <a class="nav-link" href="{% url item.link %}">{{ item.name }}
                {% if request.resolver_match.url_name == item.link %}
                <span class="sr-only">(current)</span>
                {% endif %}
              </a>
            </li>

                {% endfor %}
            </ul>
        </div>
    </div>
</nav>